### ISSUE TITLE
consegna project plan 

### ISSUE THREAD

**Issue by SickCeco** [MaccariLuca/fakeinvaders#7]
[Project Plan.docx](https://github.com/MaccariLuca/fakeinvaders/files/13752087/Project.Plan.docx)

**Comment by garganti** [comment]
devi assegnarmelo non citarmi !

**Comment by garganti** [comment]
approvato. Un paio di cose non tornano:

- come editor è importante che poi funzioni sotto eclipse per me che lo correggo. Voi citate anche VSC ma non ho capito per cosa
- la consegna del progetto è qualche giorno prima della presentazione, non per lo scritto

**Comment by MaccariLuca** [comment]
@garganti 
Buonasera,
Grazie per la delucidazione sulla consegna.
Per quanto riguarda Visual Studio Code, l'utilizzo rimane circoscritto nella fase di sviluppo del software, che poi sarà comunque presentato interamente su Eclipse

**Comment by garganti** [comment]
ok, VSC è ottimo. Però importante è che poi se apro eclipse e importo il vostro progetto funzioni tutto.
